### ISSUE TITLE
crash with gregtech 2.4.0 and htmlTech-1.12.2-0.2.2-beta

### ISSUE THREAD

**Issue by blakpsykozz27** [htmlcsjs/htmlTech#6]
Time: 2022-08-19 18:52:41 CEST
Description: Initializing game

java.lang.ClassCastException: gregtech.api.items.metaitem.MetaItem$MetaValueItem cannot be cast to net.minecraft.item.ItemStack
    at net.htmlcsjs.htmlTech.loaders.recipe.LaserEquipmentLoader.init(LaserEquipmentLoader.java:58)
    at net.htmlcsjs.htmlTech.loaders.HTRecipeManiger.init(HTRecipeManiger.java:10)
    at net.htmlcsjs.htmlTech.proxy.CommonProxy.registerRecipes(CommonProxy.java:38)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1741_CommonProxy_registerRecipes_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by htmlcsjs** [comment]
fucks sake

**Comment by htmlcsjs** [comment]
works for me, can you please send your modlist?

**Comment by htmlcsjs** [comment]
fucking gcys

**Comment by blakpsykozz27** [comment]
CodeChickenLib-1.12.2-3.2.3.358-universal
CTM-MC1.12.2-1.0.2.31
GregicalityMultiblocks-1.12.2-1.1.4
GregicalityScience-1.12.2-0.0.1
GregTech+Food+Option-1.12.2-1.7.0.1
gregtech-1.12.2-2.4.0-gcys-alpha
htmlTech-1.12.2-0.2.2-beta

**Comment by htmlcsjs** [comment]
i have debugged that (i suspected it) and its an incompat with gcys. I am going to wait for 0.0.2 or an update to the ceu that gcys needs to debug further

**Comment by blakpsykozz27** [comment]
OK no problem 😉
